---
title: "Escolaridad y medio de transporte"
format: 
    html:
        toc: true
        hmtl-math-method: katex
        embed-resources: true
        df-print: kable
editor: source
---

## Pregunta

*¿El nivel de escolaridad de una persona influye en el medio de transporte que más utiliza?*

```{r}
#| eval: false
#| echo: false

install.packages("bnlearn")
```


```{r}
library(bnlearn)
```


```{r}
data = read.csv("data/clean_enmt_unam.csv", stringsAsFactors = TRUE)
head(data)
```

```{r}
df = data[, c("edad_1", "sexo", "escol", "p1a_12", "p1a_4", "p1a_16")]
names(df) = c("edad", "sexo", "escol", "auto", "camion", "bici")

# se eliminan los codigos de NS/NC (8 y 9)
df = df[df$escol %in% 1:5 &
        df$auto %in% 1:3 &
        df$camion %in% 1:3 &
        df$bici %in% 1:3, ]

df$edad   = factor(df$edad, levels = 2:7,
                   labels = c("15-24", "25-34", "35-44", "45-54", "55-64", "65+"))
df$sexo   = factor(df$sexo, levels = 1:2, labels = c("H", "M"))
df$escol  = factor(df$escol, levels = 1:5,
                   labels = c("ninguna", "primaria", "secundaria", "prepa", "uni"))
df$auto   = factor(df$auto,   levels = 1:3, labels = c("cotidiano", "ocasional", "no_usa"))
df$camion = factor(df$camion, levels = 1:3, labels = c("cotidiano", "ocasional", "no_usa"))
df$bici   = factor(df$bici,   levels = 1:3, labels = c("cotidiano", "ocasional", "no_usa"))

df = na.omit(df)
summary(df)
```

```{r}
dag = empty.graph(nodes = c("edad", "sexo", "escol", "auto", "camion", "bici"))
```

```{r}
arc_set = matrix(c("edad", "escol",
                   "sexo", "escol",
                   "escol", "auto",
                   "escol", "camion",
                   "escol", "bici",
                   "edad", "auto",
                   "edad", "camion",
                   "edad", "bici"),
                 byrow = TRUE, ncol = 2,
                 dimnames = list(NULL, c("from", "to")))
```

```{r}
arcs(dag) = arc_set
dag
```


```{r}
bn_mle = bn.fit(dag, data = df, method = "mle")
bn_mle
```

```{r}
bn_mle$escol
bn_mle$auto
```

```{r}
ci.test('auto', 'escol', c('edad'), test = 'mi', data = df)
```

```{r}
ci.test('auto', 'escol', c('edad'), test = 'x2', data = df)
```

```{r}
ci.test('camion', 'escol', c('edad'), test = 'mi', data = df)
```

```{r}
ci.test('bici', 'escol', c('edad'), test = 'mi', data = df)
```

```{r}
arc.strength(dag, data = df, criterion = "mi")
```

```{r}
score(dag, data = df, type = "bic")
```

```{r}
score(dag, data = df, type = "aic")
```

```{r}
best_dag = hc(df)
best_dag
```

```{r}
modelstring(best_dag)
```

```{r}
score(best_dag, data = df, type = 'bic')
score(best_dag, data = df, type = 'aic')
```

```{r}
#| eval: false
#| echo: false
install.packages("BiocManager")
BiocManager::install("Rgraphviz")
```

```{r}
graphviz.plot(best_dag, shape = "ellipse")
```

```{r}
bn = bn.fit(best_dag, data = df)
```

*¿El nivel de escolaridad de una persona influye en el medio de transporte que más utiliza?*

**Automóvil particular de uso cotidiano**
```{r}
set.seed(42)
cpquery(bn, event = (auto == "cotidiano"), evidence = (escol == "uni"), n = 10^6)
cpquery(bn, event = (auto == "cotidiano"), evidence = (escol == "primaria"), n = 10^6)
```

**Camión/microbús de uso cotidiano**
```{r}
cpquery(bn, event = (camion == "cotidiano"), evidence = (escol == "uni"), n = 10^6)
cpquery(bn, event = (camion == "cotidiano"), evidence = (escol == "primaria"), n = 10^6)
```

**Bicicleta de uso cotidiano**
```{r}
cpquery(bn, event = (bici == "cotidiano"), evidence = (escol == "uni"), n = 10^6)
cpquery(bn, event = (bici == "cotidiano"), evidence = (escol == "primaria"), n = 10^6)
```

```{r}
cpquery(bn, event = (auto == "cotidiano"), evidence = list(escol = "uni"), method = "lw")
```
